# Generated by Django 2.2.1 on 2019-05-10 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
