# Generated by Django 2.2.1 on 2019-05-10 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_developer_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_entity',
        ),
    ]
